# Generated by Django 3.2.16 on 2022-11-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
