# Generated by Django 3.2.16 on 2022-11-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_django', '0002_remove_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Room name'),
        ),
    ]
