# Generated by Django 3.2.16 on 2022-11-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_django', '0003_auto_20221107_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(default='07.11.2022 11:02:08'),
        ),
    ]
