# Generated by Django 3.2.16 on 2022-11-09 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_django', '0005_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='online',
            field=models.ManyToManyField(blank=True, related_name='_chat_django_message_online_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
