# Generated by Django 3.2.16 on 2022-11-09 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_django', '0006_auto_20221109_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='online',
        ),
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_chat_django_message_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
