# Generated by Django 3.2.16 on 2022-11-09 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_django', '0007_auto_20221109_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_chat_django_room_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
